(0, '0.client-channel.google.com', 1, 'In order for users on your network to access Google Drive and Google Docs editors this domain must be whitelisted - https://support.google.com/a/answer/2589954?hl=en  - qjz9zk')
(0, '1drv.com', 1, 'It is actually a legitimate Microsoft owned domain and used as a short link for OneDrive documents. - qjz9zk')
(0, '2.android.pool.ntp.org', 1, 'This domain is a part of The pool.ntp.org project which is a big virtual cluster of timeservers providing reliable time. This domain is used in Android devices - qjz9zk')
(0, 'akamaihd.net', 1, 'This domain is owned by Akamai Technologies which is a is a global content delivery network (CDN). - qjz9zk')
(0, 'akamaitechnologies.com', 1, 'This domain is owned by Akamai Technologies which is a is a global content delivery network (CDN). - qjz9zk')
(0, 'akamaized.net', 1, 'This domain is owned by Akamai Technologies which is a is a global content delivery network (CDN). - qjz9zk')
(0, 'amazonaws.com', 1, 'Amazon Web Services (AWS) is a subsidiary of Amazon providing on-demand cloud computing platforms and APIs. This domain is used to serve files and other static resources which are hosted on Amazon AWS - qjz9zk')
(0, 'android.clients.google.com', 1, 'Google Play Store and few devices (especially Android One devices) depends on this domain for system updates. - qjz9zk')
(0, 'api.ipify.org', 1, 'It is used to get your public IP address programmatically. ipify is completely opensource. - qjz9zk')
(0, 'app-api.ted.com', 1, 'Used by ted.com streams. - qjz9zk')
(0, 'api.rlje.net', 1, 'Used to deliver contents on video straming apps on hulu etc. - qjz9zk')
(0, 'appleid.apple.com', 1, 'Used to sign in t your Apple account. - qjz9zk')
(0, 'apps.skype.com', 1, 'Used to make group calls, group chats etc. on Skype. - qjz9zk')
(0, 'appsbackup-pa.clients6.google.com', 1, 'Used to backup device settings and app data. - qjz9zk')
(0, 'appsbackup-pa.googleapis.com', 1, 'Used to backup device settings and app data. - qjz9zk')
(0, 'apt.sonarr.tv', 1, 'Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available. - qjz9zk')
(0, 'aspnetcdn.com', 1, 'Owned by Microsoft. Used to deliver files such as Windows updates and other services. - qjz9zk')
(0, 'attestation.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'ax.phobos.apple.com.edgesuite.net', 1, 'Used by Apple Photos. - qjz9zk')
(0, 'brightcove.net', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'c.s-microsoft.com', 1, 'Used to deliver fonts. - qjz9zk')
(0, 'cdn.cloudflare.net', 1, 'Used to deliver static files over CloudFlare CDN. - qjz9zk')
(0, 'cdn.embedly.com', 1, 'Embedly is used to embed videos, images and rich media from 300+ providers with just the URL. - qjz9zk')
(0, 'cdn.optimizely.com', 1, 'optimizely.com is a progressive delivery and experimentation software for other companies. Often used as a video delivery system. - qjz9zk')
(0, 'cdn.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'cdn2.optimizely.com', 1, 'optimizely.com is a progressive delivery and experimentation software for other companies. Often used as a video delivery system. - qjz9zk')
(0, 'cdn3.optimizely.com', 1, 'optimizely.com is a progressive delivery and experimentation software for other companies. Often used as a video delivery system. - qjz9zk')
(0, 'cdnjs.cloudflare.com', 1, 'Used to deliver static files over CloudFlare CDN. - qjz9zk')
(0, 'cert.mgt.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'clientconfig.passport.net', 1, 'Owned by Microsoft. Used in Windows Store. - qjz9zk')
(0, 'clients1.google.com', 1, 'Used in Google Maps and other Google services. - qjz9zk')
(0, 'clients2.google.com', 1, 'Used in Google Maps and other Google services. - qjz9zk')
(0, 'clients3.google.com', 1, 'Used in Google Maps and other Google services. - qjz9zk')
(0, 'clients4.google.com', 1, 'Used in Google Maps and other Google services. - qjz9zk')
(0, 'clients5.google.com', 1, 'Used in Google Maps and other Google services. - qjz9zk')
(0, 'clients6.google.com', 1, 'Used in Google Maps and other Google services. - qjz9zk')
(0, 'cpms.spop10.ams.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'cpms35.spop10.ams.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'cse.google.com', 1, 'Google Custom Search. Often used as a search functionality inside a website. https://programmablesearchengine.google.com/about/ - qjz9zk')
(0, 'ctldl.windowsupdate.com', 1, 'Owned by Microsoft. Used to deliver Windows updates. - qjz9zk')
(0, 'cws.conviva.com', 1, 'Conviva offers online video optimization and online video analytics. But it is neccessary to whitelist in order to watch many online contents which uses Conviva. - qjz9zk')
(0, 'livepassdl.conviva.com', 1, 'Conviva offers online video optimization and online video analytics. But it is neccessary to whitelist in order to watch many online contents which uses Conviva. - qjz9zk')
(0, 'zee.cws.conviva.com', 1, 'Conviva offers online video optimization and online video analytics. But it is neccessary to whitelist in order to watch many online contents which uses Conviva. - qjz9zk')
(0, 'pings.conviva.com', 1, 'Conviva offers online video optimization and online video analytics. But it is neccessary to whitelist in order to watch many online contents which uses Conviva. - qjz9zk')
(0, 'gfwsl.geforce.com', 1, 'Used for checking nVidia driver updates. - qjz9zk')
(0, 'appspot-preview.l.google.com', 1, 'Used to deliver system updates to Moto phones. - qjz9zk')
(0, 'd2c8v52ll5s99u.cloudfront.net', 1, 'Domain owned by Amazon. Used to deliver media such as videos in entertainment and news sites. - qjz9zk')
(0, 'd2gatte9o95jao.cloudfront.net', 1, 'Domain owned by Amazon. Used to deliver media such as videos in entertainment and news sites. - qjz9zk')
(0, 'dashboard.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'dataplicity.com', 1, 'Used to remotely control your Raspberry-Pi. - qjz9zk')
(0, 'def-vef.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'delivery.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'dev.virtualearth.net', 1, 'Owned by Microsoft. Used by Bing Maps to get information about various places. For example, this domain should be whitelisted in order to select a store location on costco.com.  - qjz9zk')
(0, 'device.auth.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'display.ugc.bazaarvoice.com', 1, 'To display Ratings & Reviews or Questions & Answers in online stores. - qjz9zk')
(0, 'displaycatalog.mp.microsoft.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'dl.delivery.mp.microsoft.com', 1, 'Used to deliver updates to Microsoft products. - qjz9zk')
(0, 'dl.dropbox.com', 1, 'Used to download files from Dropbox - qjz9zk')
(0, 'dl.dropboxusercontent.com', 1, 'Used to download files from Dropbox - qjz9zk')
(0, 'dns.msftncsi.com', 1, 'Owned by Microsoft. Used to check whether the internet connection is up or not in Windows systems.  - qjz9zk')
(0, 'download.sonarr.tv', 1, 'Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available. - qjz9zk')
(0, 'drift.com', 1, 'Live chat platform for websites to chat with the website owner. Blocking this domain will block chat widget. - qjz9zk')
(0, 'driftt.com', 1, 'Live chat platform for websites to chat with the website owner. Blocking this domain will block chat widget. - qjz9zk')
(0, 'dynupdate.no-ip.com', 1, 'No-IP offers DNS services, email, network monitoring and SSL certificates - qjz9zk')
(0, 'ecn.dev.virtualearth.net', 1, 'Owned by Microsoft. Used by Bing Maps to get information about various places. For example, this domain should be whitelisted in order to select a store location on costco.com. - qjz9zk')
(0, 'edge.api.brightcove.com', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'eds.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'fonts.gstatic.com', 1, 'Owned by Google. Used to deliver Google Fonts. - qjz9zk')
(0, 'forums.sonarr.tv', 1, 'Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available. - qjz9zk')
(0, 'g.live.com', 1, 'Used by Microsoft for their Outlook.com and OneDrive products. Backup bitlocker recovery key to Microsoft account. - qjz9zk')
(0, 'geo-prod.do.dsp.mp.microsoft.com', 1, 'Enables connections to Windows Update. - qjz9zk')
(0, 'geo3.ggpht.com', 1, 'Owned by Google. Used to deliver static files over the internet. - qjz9zk')
(0, 'giphy.com', 1, 'Gifs hosting platform. - qjz9zk')
(0, 'github.com', 1, 'GitHub provides hosting for software development and version control using Git. - qjz9zk')
(0, 'github.io', 1, 'Owned by GitHub. Used for GitHub pages. - qjz9zk')
(0, 'googleapis.com', 1, 'An important domain used to provide APIs to various Google services. - qjz9zk')
(0, 'gravatar.com', 1, 'Owned by Automattic. Gravatar is a service for providing globally unique avatars - qjz9zk')
(0, 'gstatic.com', 1, 'Owned by Google. gstatic.com is a cookieless domain to deliver static content for Google. - qjz9zk')
(0, 'help.ui.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'hls.ted.com', 1, 'Used by ted.com streams. - qjz9zk')
(0, 'i.ytimg.com', 1, 'Owned by Google. Used to deliver thumbails in YouTube. - qjz9zk')
(0, 'i1.ytimg.com', 1, 'Owned by Google. Used to deliver thumbails in YouTube. - qjz9zk')
(0, 'imagesak.secureserver.net', 1, 'GoDaddy webmail buttons - qjz9zk')
(0, 'img.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'imgix.net', 1, 'Image placeholders often used during web page loading. - qjz9zk')
(0, 'imgs.xkcd.com', 1, 'Used to deliver images on xkcd.com. - qjz9zk')
(0, 'instantmessaging-pa.googleapis.com', 1, 'An important domain used to provide APIs to various Google services. - qjz9zk')
(0, 'intercom.io', 1, 'Live chat platform for websites to chat with the website owner. Blocking this domain will block chat widget. - qjz9zk')
(0, 'jquery.com', 1, 'jQuery is a JavaScript library. Also used to deliver the files over CDN. - qjz9zk')
(0, 'jsdelivr.net', 1, ' jsDelivr is a free public CDN for open-source projects. It can serve web files directly from the npm registry and GitHub repositories without any configuration. - qjz9zk')
(0, 'keystone.mwbsys.com', 1, 'Owned by Malwarebytes. It is a licensing system used to verify the Malwarebytes software license. - qjz9zk')
(0, 'lastfm-img2.akamaized.net', 1, 'Used by last.fm to deliver images. - qjz9zk')
(0, 'licensing.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'live.com', 1, 'Owned by Microsoft. It is a personal information manager web app from Microsoft consisting of webmail, calendaring, contacts, and tasks services. - qjz9zk')
(0, 'login.live.com', 1, 'Owned by Microsoft. The following endpoint is used to authenticate a device.  - qjz9zk')
(0, 'login.microsoftonline.com', 1, 'Owned by Microsoft. Used by Microsoft Office apps. - qjz9zk')
(0, 'manifest.googlevideo.com', 1, 'Used for YouTube live streams. - qjz9zk')
(0, 'meta-db-worker02.pop.ric.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'meta.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'meta.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'microsoftonline.com', 1, 'Owned by Microsoft. This domain is checked by the operating systems when connecting via wifi, and if they do not get the response they expect, they may try to open a wifi login page or similar as they believe they are located behind a captive portal. - qjz9zk')
(0, 'msftncsi.com', 1, 'Owned by Microsoft. This domain is checked by the operating systems when connecting via wifi, and if they do not get the response they expect, they may try to open a wifi login page or similar as they believe they are located behind a captive portal. - qjz9zk')
(0, 'my.plexapp.com', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'nexusrules.officeapps.live.com', 1, 'Owned by Microsoft. Used by Microsoft Office apps. - qjz9zk')
(0, 'npr-news.streaming.adswizz.com', 1, 'Used for NPR morning news and podcasts. - qjz9zk')
(0, 'nine.plugins.plexapp.com', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'no-ip.com', 1, 'No-IP offers DNS services, email, network monitoring and SSL certificates. - qjz9zk')
(0, 'node.plexapp.com', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'notify.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'ns1.dropbox.com', 1, 'Dropbox nameserver. Used to download files from Dropbox - qjz9zk')
(0, 'ns2.dropbox.com', 1, 'Dropbox nameserver. Used to download files from Dropbox - qjz9zk')
(0, 'o1.email.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'o2.sg0.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'ocsp.apple.com', 1, 'iOS developers are able to distribute apps outside of the App Store using an Enterprise provisioning profile. Apple can revoke these kinds of apps by using this domain. - qjz9zk')
(0, 'office.com', 1, 'Owned by Microsoft. Used by Microsoft Office apps. - qjz9zk')
(0, 'office.net', 1, 'Owned by Microsoft. Used by Microsoft Office apps. - qjz9zk')
(0, 'office365.com', 1, 'Owned by Microsoft. Used by Microsoft Office apps. - qjz9zk')
(0, 'officeclient.microsoft.com', 1, 'Used by Microsoft Office apps. - qjz9zk')
(0, 'om.cbsi.com', 1, 'CBS All Access on straming platforms. - qjz9zk')
(0, 'onedrive.live.com', 1, 'Owned by Microsoft. Used to sign in to One Drive. - qjz9zk')
(0, 'outlook.live.com', 1, 'Owned by Microsoft. Used for Outlook email. - qjz9zk')
(0, 'outlook.office365.com', 1, 'Owned by Microsoft. Used for Outlook email.ent - qjz9zk')
(0, 'placehold.it', 1, 'Placehold.it, Image placeholders often used during web page loading. - qjz9zk')
(0, 'placeholdit.imgix.net', 1, 'Placehold.it, Image placeholders often used during web page loading. - qjz9zk')
(0, 'players.brightcove.net', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'pricelist.skype.com', 1, 'Used to make group calls, group chats etc. on Skype. - qjz9zk')
(0, 'products.office.com', 1, 'Owned by Microsoft. Used by Microsoft Office apps. - qjz9zk')
(0, 'proxy.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'proxy.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'proxy02.pop.ord.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'pubsub.plex.bz', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'pubsub.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'raw.githubusercontent.com', 1, 'Owned by GitHub. It is used to serve unprocessed versions of files stored in GitHub repositories.  - qjz9zk')
(0, 'redirector.googlevideo.com', 1, 'Used by YouTube to play embedded videos on third-party websites. - qjz9zk')
(0, 'res.cloudinary.com', 1, 'Cloudinary provides a cloud-based image and video management services. It enables users to upload, store, manage, manipulate, and deliver images and video for websites and apps. - qjz9zk')
(0, 's.gateway.messenger.live.com', 1, 'Owned by Microsoft. It is a personal information manager web app from Microsoft consisting of webmail, calendaring, contacts, and tasks services. - qjz9zk')
(0, 's.marketwatch.com', 1, 'Images are loaded on marketwatch.com using this domain. - qjz9zk')
(0, 's.youtube.com', 1, 'Used to record YouTube watch history. Blocking this domain will pause your watch history on YouTube. - qjz9zk')
(0, 's.ytimg.com', 1, 'Owned by Google. Used to deliver thumbails in YouTube. - qjz9zk')
(0, 's1.wp.com', 1, 'Owned by WordPress. Used to feliver static files and media for websites which are hosted on wordpress.com platform. - qjz9zk')
(0, 's2.youtube.com', 1, 'Used to record YouTube watch history. Blocking this domain will pause your watch history on YouTube. - qjz9zk')
(0, 's3.amazonaws.com', 1, 'Used to deliver files that are stored in Amazon AWS S3 storage buckets. - qjz9zk')
(0, 'sa.symcb.com', 1, 'Owned by Symantec. These are Symantec Certificate Revocation List servers and are used by a number of companies including Microsoft. - qjz9zk')
(0, 'secure.avangate.com', 1, 'Used to perform online payments. - qjz9zk')
(0, 'secure.brightcove.com', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'secure.surveymonkey.com', 1, 'Used by Survey Monkey to deliver surveys. - qjz9zk')
(0, 'services.sonarr.tv', 1, 'Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available. - qjz9zk')
(0, 'skyhook.sonarr.tv', 1, 'Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available. - qjz9zk')
(0, 'spclient.wg.spotify.com', 1, 'Spotify on Web and desktop player does not work if this domain is blocked. - qjz9zk')
(0, 'ssl.p.jwpcdn.com', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'staging.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'status.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 't.co', 1, 'Owned by Twitter. Used as a URL shortner while sharing Twitter posts. - qjz9zk')
(0, 't0.ssl.ak.dynamic.tiles.virtualearth.net', 1, 'Owned by Microsoft. Used by Bing Maps to get information about various places. For example, this domain should be whitelisted in order to select a store location on costco.com. - qjz9zk')
(0, 't0.ssl.ak.tiles.virtualearth.net', 1, 'Owned by Microsoft. Used by Bing Maps to get information about various places. For example, this domain should be whitelisted in order to select a store location on costco.com. - qjz9zk')
(0, 'tawk.to', 1, 'Live chat platform for websites to chat with the website owner. Blocking this domain will block chat widget. - qjz9zk')
(0, 'tedcdn.com', 1, 'Used by ted.com streams. - qjz9zk')
(0, 'themoviedb.com', 1, 'Metadata for movies - qjz9zk')
(0, 'thetvdb.com', 1, 'Metadata for TV series - qjz9zk')
(0, 'tinyurl.com', 1, 'Popular URL shortner - qjz9zk')
(0, 'title.auth.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'title.mgt.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'traffic.libsyn.com', 1, 'Used in Pocketcasts app to serve and download podcasts. - qjz9zk')
(0, 'tvdb2.plex.tv', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'tvthemes.plexapp.com', 1, 'Plex is a client–server media player system plus an ancillary software suite. - qjz9zk')
(0, 'twimg.com', 1, 'Owned by Twitter. Used to deliver media on Twitter. - qjz9zk')
(0, 'ui.skype.com', 1, 'Used to make group calls, group chats etc. on Skype. - qjz9zk')
(0, 'video-stats.l.google.com', 1, 'Used to record YouTube watch history. Blocking this domain will pause your watch history on YouTube. - qjz9zk')
(0, 'videos.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites. - qjz9zk')
(0, 'widget-cdn.rpxnow.com', 1, 'Owned by Akamai Technologies. Used as a sign in method in various apps and sites. - qjz9zk')
(0, 'win10.ipv6.microsoft.com', 1, 'It gives full IPv6 connectivity for IPv6-capable hosts that are on the IPv4 Internet but have no native connection to an IPv6 network.  - qjz9zk')
(0, 'wp.com', 1, 'Owned by WordPress.com hosting. - qjz9zk')
(0, 'ws.audioscrobbler.com', 1, 'Owned by last.fm. Used to get track metadata using last.fm API. - qjz9zk')
(0, 'www.dataplicity.com', 1, 'Used to remotely control your Raspberry-Pi. - qjz9zk')
(0, 'www.googleapis.com', 1, 'An important domain used to provide APIs to various Google services.  - qjz9zk')
(0, 'www.msftncsi.com', 1, 'Owned by Microsoft. This domain is checked by the operating systems when connecting via wifi, and if they do not get the response they expect, they may try to open a wifi login page or similar as they believe they are located behind a captive portal. - qjz9zk')
(0, 'www.no-ip.com', 1, 'No-IP offers DNS services, email, network monitoring and SSL certificates. - qjz9zk')
(0, 'www.youtube-nocookie.com', 1, 'Owned by Google. YouTube launched a new feature on the site recently that it called Privacy-Enhanced Mode. This domain is used to embed the videos on third-party sites with less trackers. - qjz9zk')
(0, 'xbox.ipv6.microsoft.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'xboxexperiencesprod.experimentation.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'xflight.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'xkms.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'xsts.auth.xboxlive.com', 1, 'Owned by Microsoft. Used for Xbox updates, game downloads, acheivements unlocking etc. - qjz9zk')
(0, 'youtube-nocookie.com', 1, 'Owned by Google. YouTube launched a new feature on the site recently that it called Privacy-Enhanced Mode. This domain is used to embed the videos on third-party sites with less trackers. - qjz9zk')
(0, 'youtu.be', 1, 'YouTube URL shortner. Used while sharing videos, playlists, channels etc. - qjz9zk')
(0, 'yt3.ggpht.com', 1, 'Owned by Google. Used to deliver static files over the internet. - qjz9zk')
(0, 'vidtech.cbsinteractive.com', 1, 'Used to deliver videos over the internet. - qjz9zk')
(0, 'continuum.dds.microsoft.com', 1, 'Used by YourPhone app by Microsoft on Windows 10 for mirroring Android notifications - qjz9zk')
(0, 'connectivitycheck.gstatic.com', 1, 'Owned by Google. Used by mobiles devices to check internet connectivity. Also known as Network Connectivity Status Indicator-NCSI. - qjz9zk')
(0, 'connectivitycheck.android.com', 1, 'Owned by Google. Used by mobiles devices to check internet connectivity. Also known as Network Connectivity Status Indicator-NCSI. - qjz9zk')
(0, 'www.msftconnecttest.com', 1, 'Owned by Microsoft. Used by Windows systems to check internet connectivity. Also known as Network Connectivity Status Indicator-NCSI. - qjz9zk')
